version: "3.8"

services:
  mongodb:
    container_name: chat-mongo
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=mongoadmin
      - MONGO_INITDB_DATABASE=chat
    volumes:
      - ./docker/mongo/init.js:/docker-entrypoint-initdb.d/init.js
  app:
    container_name: chat-app
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    env_file:
      - ./.env
    environment:
      # - NODE_ENV=production
      # - NODE_DEBUG=false
      - NODE_ENV=local
      - NODE_DEBUG=true
      - NODE_PORT=${NODE_PORT}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - MONGO_DSN=${MONGO_DSN}
    volumes:
      - ./:/usr/src/app
    command: ['npm', 'run', 'dev']